# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
name: Build and deploy Node.js app to Azure Web App - nextalk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'

      - name: npm install, build, and test
        working-directory: server
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload server artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_91EFB3E3ECF546AB9436FCACB81E43FA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3C045A24E7554A0CBBB4EE09B3B5DE36 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_415C24DF3E6E46CE9E8C617CC7201ECC }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nextalk'
          slot-name: 'Production'
          package: .
